### ISSUE TITLE
Segfault in recurseKnn() . Does it run out of stack space?

### ISSUE THREAD

**Issue by tcies** [ethz-asl/libnabo#34]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3302b8d in unsigned long Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::recurseKnn<false, false>(double const*, unsigned int, double, Nabo::IndexHeapBruteForceVector<int, double>&, std::vector<double, std::allocator<double> >&, double, double) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
(gdb) bt
#0  0x00007ffff3302b8d in unsigned long Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::recurseKnn<false, false>(double const*, unsigned int, double, Nabo::IndexHeapBruteForceVector<int, double>&, std::vector<double, std::allocator<double> >&, double, double) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
#1  0x00007ffff3302cbf in unsigned long Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::recurseKnn<false, false>(double const*, unsigned int, double, Nabo::IndexHeapBruteForceVector<int, double>&, std::vector<double, std::allocator<double> >&, double, double) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
#2  0x00007ffff3302cbf in unsigned long Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::recurseKnn<false, false>(double const*, unsigned int, double, Nabo::IndexHeapBruteForceVector<int, double>&, std::vector<double, std::allocator<double> >&, double, double) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
#3  0x00007ffff3302cbf in unsigned long Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::recurseKnn<false, false>(double const*, unsigned int, double, Nabo::IndexHeapBruteForceVector<int, double>&, std::vector<double, std::allocator<double> >&, double, double) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
```
[...]
```
#54 0x00007ffff3302aa4 in unsigned long Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::recurseKnn<false, false>(double const*, unsigned int, double, Nabo::IndexHeapBruteForceVector<int, double>&, std::vector<double, std::allocator<double> >&, double, double) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
#55 0x00007ffff3302e89 in Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::onePointKnn(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, -1, 0, -1, -1>&, Eigen::Matrix<double, -1, -1, 0, -1, -1>&, int, Nabo::IndexHeapBruteForceVector<int, double>&, std::vector<double, std::allocator<double> >&, double, double, bool, bool, bool) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
#56 0x00007ffff3303131 in Nabo::KDTreeUnbalancedPtInLeavesImplicitBoundsStackOpt<double, Nabo::IndexHeapBruteForceVector<int, double> >::knn(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<int, -1, -1, 0, -1, -1>&, Eigen::Matrix<double, -1, -1, 0, -1, -1>&, int, double, unsigned int, double) const () from /home/titus/catkin_ws/devel/lib/libdescriptor_projection.so
#57 0x00007ffff5f7edd9 in structural_descriptors::RawNbld::RawNbld (this=0x7fffffffd200, mission=..., options=...)
    at /home/titus/catkin_ws/src/multiagent_mapping/vi-algorithms/structural-descriptors/src/raw-nbld.cc:45
```
This is querying 200 nearest neighbours with a query size of 10000 against 775835 in 3 dimensions. Error tolerance is 0.

**Comment by simonlynen** [comment]
You are probably using the code wrong. Libnabo requires MatrixXf and not Matrix3Xf. It compiles with the wrong type since they derive from the same base, but it is wrong. See here https://github.com/ethz-asl/libnabo/issues/9

**Comment by simonlynen** [comment]
@tcies also "stack" here refers to the abstract data type stack, not to the type of memory allocation.

**Comment by tcies** [comment]
Thanks, that seemed to do the trick.
